'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18444
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace My
	
	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
	 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "4.4.1.9729"),  _
	 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
	Partial Friend NotInheritable Class MySettings
		Inherits Global.System.Configuration.ApplicationSettingsBase
		
		Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
		
		#Region "Support for My.Application.SaveMySettingsOnExit"
		#If _MyType = "WindowsForms" Then
		Private Shared addedHandler As Boolean
		Private Shared addedHandlerLockObject As New Object

		<Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
			If My.Application.SaveMySettingsOnExit Then
				My.Settings.Save()
			End If
		End Sub
		#End If
		#End Region
		
		Public Shared ReadOnly Property [Default]() As MySettings
			Get
				#If _MyType = "WindowsForms" Then
				If Not addedHandler Then
					SyncLock addedHandlerLockObject
						If Not addedHandler Then
							AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
							addedHandler = True
						End If
					End SyncLock
				End If
				#End If
				Return defaultInstance
			End Get
		End Property
		
		<Global.System.Configuration.UserScopedSettingAttribute(),  _
		 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
		 Global.System.Configuration.DefaultSettingValueAttribute(" a c:\temp\temp.7z ")>  _
		Public Property cmd1() As String
			Get
				Return CType(Me("cmd1"),String)
			End Get
			Set
				Me("cmd1") = value
			End Set
		End Property
		
		<Global.System.Configuration.UserScopedSettingAttribute(),  _
		 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
		 Global.System.Configuration.DefaultSettingValueAttribute(" a -sfx7z.sfx ")>  _
		Public Property cmd2() As String
			Get
				Return CType(Me("cmd2"),String)
			End Get
			Set
				Me("cmd2") = value
			End Set
		End Property
		
		<Global.System.Configuration.UserScopedSettingAttribute(),  _
		 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
		 Global.System.Configuration.DefaultSettingValueAttribute(" /C copy /b ")>  _
		Public Property cmd3() As String
			Get
				Return CType(Me("cmd3"),String)
			End Get
			Set
				Me("cmd3") = value
			End Set
		End Property
		
		<Global.System.Configuration.UserScopedSettingAttribute(),  _
		 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
		 Global.System.Configuration.DefaultSettingValueAttribute("7za.exe")>  _
		Public Property exe7za() As String
			Get
				Return CType(Me("exe7za"),String)
			End Get
			Set
				Me("exe7za") = value
			End Set
		End Property
	End Class
	
	<Microsoft.VisualBasic.HideModuleNameAttribute(),  _
	 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
	 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
	Friend Module MySettingsProperty
		
		<Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
		Friend ReadOnly Property Settings() As My.MySettings
			Get
				Return My.MySettings.Default
			End Get
		End Property
	End Module
End Namespace
